apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: transaction-risk-api
  namespace: transaction-risk
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transaction-risk-api
