"""Feature extraction and preprocessing for Sprint 2 model training."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import pandas as pd
from pandas.api.types import is_numeric_dtype
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


class FeaturePreparationError(ValueError):
    """Raised when a training frame cannot be prepared."""


@dataclass(frozen=True)
class PreparedFeatureFrame:
    """Feature matrix and target extracted from a tabular dataset."""

    features: pd.DataFrame
    target: pd.Series


class FeaturePreprocessor:
    """Fit preprocessing on train and reuse it for validation/test data."""

    def __init__(self, feature_columns: tuple[str, ...], target_column: str) -> None:
        if not feature_columns:
            raise FeaturePreparationError("feature_columns must not be empty")
        if target_column in feature_columns:
            raise FeaturePreparationError("target_column cannot be a model feature")
        self.feature_columns = feature_columns
        self.target_column = target_column
        self.numeric_columns: tuple[str, ...] = ()
        self.categorical_columns: tuple[str, ...] = ()
        self._transformer: ColumnTransformer | None = None

    def fit(self, train_frame: pd.DataFrame) -> FeaturePreprocessor:
        features = _select_features(
            train_frame,
            feature_columns=self.feature_columns,
            target_column=self.target_column,
        )
        self.numeric_columns = tuple(
            column for column in self.feature_columns if is_numeric_dtype(features[column])
        )
        self.categorical_columns = tuple(
            column for column in self.feature_columns if column not in self.numeric_columns
        )
        if not self.numeric_columns and not self.categorical_columns:
            raise FeaturePreparationError("No usable feature columns found")

        transformers = []
        if self.numeric_columns:
            transformers.append(
                (
                    "numeric",
                    Pipeline(
                        steps=[
                            ("imputer", SimpleImputer(strategy="median")),
                            ("scaler", StandardScaler()),
                        ]
                    ),
                    list(self.numeric_columns),
                )
            )
        if self.categorical_columns:
            transformers.append(
                (
                    "categorical",
                    Pipeline(
                        steps=[
                            ("imputer", SimpleImputer(strategy="most_frequent")),
                            (
                                "encoder",
                                OneHotEncoder(
                                    handle_unknown="ignore",
                                    sparse_output=True,
                                ),
                            ),
                        ]
                    ),
                    list(self.categorical_columns),
                )
            )

        self._transformer = ColumnTransformer(
            transformers=transformers,
            remainder="drop",
            verbose_feature_names_out=False,
        )
        self._transformer.fit(features)
        return self

    def transform(self, frame: pd.DataFrame):
        """Transform a frame using state learned from ``fit``."""

        if self._transformer is None:
            raise FeaturePreparationError("FeaturePreprocessor must be fitted first")
        features = _select_features(
            frame,
            feature_columns=self.feature_columns,
            target_column=self.target_column,
        )
        return self._transformer.transform(features)

    def fit_transform(self, train_frame: pd.DataFrame):
        """Fit on train and return its transformed feature matrix."""

        self.fit(train_frame)
        return self.transform(train_frame)

    def get_feature_names_out(self) -> tuple[str, ...]:
        """Return output columns generated by the fitted transformer."""

        if self._transformer is None:
            raise FeaturePreparationError("FeaturePreprocessor must be fitted first")
        return tuple(self._transformer.get_feature_names_out())


def prepare_feature_frame(
    frame: pd.DataFrame,
    *,
    feature_columns: tuple[str, ...],
    target_column: str,
) -> PreparedFeatureFrame:
    """Extract model features and target while preserving feature order."""

    features = _select_features(
        frame,
        feature_columns=feature_columns,
        target_column=target_column,
    )
    target = frame[target_column].copy()
    return PreparedFeatureFrame(features=features, target=target)


def spark_frame_to_pandas(dataframe: Any, columns: tuple[str, ...]) -> pd.DataFrame:
    """Select columns from a Spark DataFrame and materialize a pandas frame."""

    try:
        return dataframe.select(*columns).toPandas()
    except Exception as exc:
        raise FeaturePreparationError(
            "Unable to convert the selected Spark feature columns to pandas"
        ) from exc


def _select_features(
    frame: pd.DataFrame,
    *,
    feature_columns: tuple[str, ...],
    target_column: str,
) -> pd.DataFrame:
    required_columns = set(feature_columns) | {target_column}
    missing_columns = sorted(required_columns.difference(frame.columns))
    if missing_columns:
        raise FeaturePreparationError(
            f"Feature frame is missing required columns: {missing_columns}"
        )
    return frame.loc[:, list(feature_columns)].copy()
